// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdKVMMTvYq2cVqNYAQR9qRJx1j5DgtRn0',
    appId: '1:617610978169:web:bfb6b16a727ca2d3cd85a8',
    messagingSenderId: '617610978169',
    projectId: 'calendar-scheduler-583a1',
    authDomain: 'calendar-scheduler-583a1.firebaseapp.com',
    storageBucket: 'calendar-scheduler-583a1.firebasestorage.app',
    measurementId: 'G-KF605QQB91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkvvi5jDlCKAE49rIgbiCXoeMTJZp20vE',
    appId: '1:617610978169:android:28ce6442ba74774ccd85a8',
    messagingSenderId: '617610978169',
    projectId: 'calendar-scheduler-583a1',
    storageBucket: 'calendar-scheduler-583a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWwmT-VeWLlUCsORTcPLCVfbausrPmVLw',
    appId: '1:617610978169:ios:6c5c0b3347812a59cd85a8',
    messagingSenderId: '617610978169',
    projectId: 'calendar-scheduler-583a1',
    storageBucket: 'calendar-scheduler-583a1.firebasestorage.app',
    iosBundleId: 'com.example.myflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWwmT-VeWLlUCsORTcPLCVfbausrPmVLw',
    appId: '1:617610978169:ios:6c5c0b3347812a59cd85a8',
    messagingSenderId: '617610978169',
    projectId: 'calendar-scheduler-583a1',
    storageBucket: 'calendar-scheduler-583a1.firebasestorage.app',
    iosBundleId: 'com.example.myflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdKVMMTvYq2cVqNYAQR9qRJx1j5DgtRn0',
    appId: '1:617610978169:web:995ee2ab8b81642acd85a8',
    messagingSenderId: '617610978169',
    projectId: 'calendar-scheduler-583a1',
    authDomain: 'calendar-scheduler-583a1.firebaseapp.com',
    storageBucket: 'calendar-scheduler-583a1.firebasestorage.app',
    measurementId: 'G-6JF1ERFRYE',
  );

}